version: "3.4"

services:
  zookeeper:
    image: bitnami/zookeeper
    networks:
      - cqrs_net_course
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka
    networks:
      - cqrs_net_course
    ports:
      - "9092:9092"
    restart: always
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper
  mongo-container:
    image: mongo
    networks:
      - cqrs_net_course
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - "mongodb_data_container:/data/db"
  sql-container:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    networks:
      - cqrs_net_course
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password123"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    restart: always
    volumes:
      - "sql_data_container:/data/db"


volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  mongodb_data_container:
    driver: local
  sql_data_container:
    driver: local


networks:
  cqrs_net_course:
    driver: bridge